Always optimise Android code to work around a split-dwarf bug
-Og + -gsplit-dwarf causes linker failures where identical values
get deduplicated and then references to the original duplicated
symbols sometimes are broken. This ends up looking like this:

engines/kyra/libkyra.a(animator_lok.o)(.debug_addr+0x14): error: undefined reference to 'Kyra::Animator_LoK::prepDrawAllObjects()::yOffsetTable2'
engines/sherlock/libsherlock.a(tattoo_darts.o)(.debug_addr+0x8): error: undefined reference to 'Sherlock::Tattoo::Darts::drawDartsLeft(int, int)::DART_Y1'

To work around this for the moment, since it seems to happen only
with this worker, use a different optimisation strategy by default
(which may become the default in any case for at least the popular
platforms) which avoids the triggering condition.

This may be related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81993.